// Baked by scripts/bake (npm run art:bake) from scripts/bake/props.js. Do not edit by hand.
import type { BakedSprite } from '../sprite'

export const InkAndQuill: BakedSprite = {
  width: 32, height: 71,
  palette: ["","#0b080c","#deba9b","#ab8660","#ac8e75","#ae8a68","#191c29","#bd7730","#181a26","#6b492c","#aa6f31","#906030","#aa6d2f","#a6692b","#945f2d","#ba722a","#0f1323","#141725","#141621","#171921","#171a24","#141827","#181a24","#171922","#191b28","#101424","#0f1220","#181b28","#17181f","#101422","#13151e","#050810"],
  frames: [
    'ADwBAQAeAQECAQEBAB0BAQIBAQEAHAEBAgIBAQAbAQECAQMBAQEAHAEBAgIBAQAbAQECAwEBABsBAQIBAwECAQEBABoBAQIEAQEAGgEBAgEEAQIBAQEAGwEBAgEDAQIBAQEAGgEBAgQBAQAaAQECAQUBAgIBAQAZAQECAgMBAgEBAQAaAQECBAEBABkBAQICBQECAgEBABkBAQIFAQEAGQEBAgQBAQAZAQECAgMBAgIBAQAZAQECBQEBABgBAQICAwECAgEBABkBAQICAwECAgEBABkBAQIFAQEAGAEBAgIDAQICAQEAGQEBAgUBAQAZAQECBQEBABgBAQICAwECAgEBABkBAQIFAQEAGQEBAgEEAQICAQEAGQEBAgIDAQICAQEAGQEBAgQBAQAaAQECAQUBAgIBAQAaAQECAQMBAgEBAQAaAQECBAEBABoBAQIBBQECAQEBABsBAQIDAQEAGwEBAgIBAQAcAQEDAQIBAQEAGwEBBAECAQEBABwBAQMBAgEBAQAcAQEDAQEBABwBAQUBAQEAHQEBAwEBAQAdAQEDAQEBABwBAQUBAQEAHQEBAwEBAQAZAQYAGAECBgQDAQYBAQIAFQEBBwEGBQMBBgEIAQkBAQEAFAEBCgEGBAgECwEBAQAVAQEMAQ0BCAQOAQ8BAQEAFAECEAERARICDwITAxQBAQEAEgEBFQMRAhYCEwMWARcCAQEAEAEBFQMRARgCFgcXAgEBAA4BARkBFQIRARgEFgcXAgEBAA0BARkBFQERAhgEFggXAgEBAAwBARoBEQMbARgBFgoTARwBAQEADAEBGgERAxYIEwUcAQEBAAwBARoBEQISAhYFEwccAQEBAAwBARoBEQISAxYDEwgcAQEBAAwBARoBEQISAxYCEwkcAQEBAAwBARoBEQISAxYCEwkcAQEBAAwBARoBEQESBRYBEwkcAQEBAAwBARoBHQESBRMKHAEBAQAMAQEaAR0BEgUeARMJHAEBAQAMAQEaAR0BEgUeARMJHAEBAQANAQEdARIEHgMTCAEBAA8BARIEHgMTBwEBABEBAh8BEgEeBBMDAQMAFAEJABI=',
  ],
}
