// Baked by scripts/bake (npm run art:bake) from scripts/bake/props.js. Do not edit by hand.
import type { BakedSprite } from '../sprite'

export const WallSconce: BakedSprite = {
  width: 44, height: 46,
  palette: ["","#0b080c","#0f0a0f","#130c0f","#a99690","#e6c6af","#e2bfa1","#deb893","#dab38a","#c7aa94","#c2a388","#e2be9e","#83511f","#a26426","#9d6023","#a6692b","#a26527","#ba722a","#aa6d2f","#bd762f","#ba722b","#b9732c","#aa6f31","#c07a32","#bd7730","#562f20","#542d1c","#885724","#633f1a","#bd762e","#532b19","#2d160e"],
  frames: [
    'AJkBAgAnAQMCAQMBAQMAIwEBBAEFAwYBBQEHAQgBAQEAIgEBBAEJAgoBBwMIAQEBACIBAQQBCQIKAQcDCAEBAQAiAQEEAQkCCgEHAwgBAQEAIgEBBAEJAgoBBwILAgEBACIBAQQBCQIKAQcCCQEHAQEBACIBAQQBCQIKAQcDCAEBAQAiAQEEAQkCCgEHAwgBAQEAIgEBBAEJAgoBBwMIAQEBACIBAQQBCQIKAQcDCAEBAQAiAQEEAQkCCgEHAwgBAQEAIgEBBAEJAgoBBwMIAQEBACIBAQQBCQIKAQcDCAEBAQAiAQEEAQkCCgEHAwgBAQEAIgEBBAEJAgoBBwMIAQEBACIBAQQBCQIKAQcDCAEBAQAiAQEEAQkCCgEHAwgBAQEAIgEBBAEJAgoBBwMIAQEBACIBAQQBCQIKAQcDCAEBAQAiAQEEAQkCCgEHAwgBAQEAIgEBBAEJAgoBBwMBAQAkAQEMAg0CDAEOAQEBACQBAQ8CEAERAwEBACMBARICEwMUAhUBAQEAHwEDFgIXAhMFGAEBAwAPAQ0WAhcIEwQYAgENAAEBARkNFgEXChMEFQEZDQECGQ4aARsBHAEPAQwBHQMUARECDAEOARoBGQ4BAh4qAQIeKgECHioBAQABAQUfAwEaHwMBBQAGAQEfAwEBABgBAR8DAQEACgEBHwMBAQAYAQEfAwEBAAoBAR8DAQEAGAEBHwMBAQAKAQEfAwEBABgBAR8DAQEACgEBHwMBAQAYAQEfAwEBAAoBAR8DAQEAGAEBHwMBAQAKAQEfAwEBABgBAR8DAQEACwEDABoBAwAy',
  ],
  anchors: {"flame":[22,1]},
}
